### ISSUE TITLE
No usable QR code available

### ISSUE THREAD

**Issue by jasonhjohnson** [maetio/expo-template#16]
Thanks for the awesome template! For some reason everything is working perfectly except for the QR code is saying "No available data" when I try to scan it with my iPhone. The app shows in my Expo Go app on my phone but I can't click it. Any ideas?

**Comment by kekoawong** [comment]
@jasonhjohnson thanks for submitting the issue! We were testing out [expo-dev-client](https://docs.expo.dev/eas-update/expo-dev-client/) and were running expo start with the --dev-client option. I have fixed the issue and you should be able to run it on the Expo Go app after we publish the new version. Feel free to drop us a star if you find the template helpful!

**Comment by kekoawong** [comment]
@jasonhjohnson Issue should now be fixed in the template. Please clone the repo or re-install the template and let us know if it is working.

**Comment by jasonhjohnson** [comment]
@kekoawong Thank you so much! Do you have plans to upgrade the project to v46 of the Expo SDK?

**Comment by kekoawong** [comment]
At this moment, no. We are a startup and have the focus of our development elsewhere at the moment, but have not even checked for the breaking changes here yet. Feel free to fork and submit a well-tested PR with the upgraded SDK, if you would like to help out! Or we can create another issue and get to it a different time.
